### ISSUE TITLE
Tracking Issue: Refactor to remove eth-types and mpt-zktrie

### ISSUE THREAD

**Issue by lightsing** [scroll-tech/stateless-block-verifier#44]
- [x] remove eth-types from stateless-block-verifier #43 
- [x] replace ethers by alloy-rs #43
- [x] remove mpt-zktries
- [x] remove ethers from binary
